variable word_press_vpc_id{}
variable env_prefix{}
variable database_subnet_az1_id{}
variable database_subnet_az2_id{}
variable database_security_group_id{}
variable rds_master_username{}
variable rds_master_password{}
variable rds_db_name{}
variable az_1{}
variable az_2{}